import './globals.css'
import type { Metadata } from 'next'
import { Inter, Manrope } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] });
const manrope = Manrope({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} text-black`}>{children}</body>
    </html>
  )
}
